### PR TITLE
Update zh_cn.json 1.14 and 1.15

### PR DESCRIPTION
**Pull request by Aemande123**
Update zh_cn.json 1.15 and 1.14，these two localization files are basically the same.

In addition
Can I move your mods to mcbbs?
mcbbs:https://www.mcbbs.net/
mcbbs is the largest minecraft fan forum in China.

I will not provide download sources other than Curseforge

I'm sorry to ask questions here, because of GFW, I cannot register for a twitch account, so I cannot ask questions on Curseforge.

### CODE REVIEW

**Comment by Corail31** [comment]
Hi Aemande123, thanks for the translation.
Normally, the mod is already on the chinese website (by Aikini).

**Comment by Aemande123** [comment]
> Hi Aemande123, thanks for the translation.
> Normally, the mod is already on the chinese website (by Aikini).
> Are you from a team of translators? Nuclear Fusion ? Kai Hua Zu ?

Hello Aikini
mcbbs does not have your mods, because the administrator of mcbbs stipulates that it can only be reproduced with the author's permission.
There is a mods reward list on mcbbs. Those who have obtained the author's reprint authorization of the mods above will be rewarded with forum points, and your mods are above.
reward list:https://www.mcbbs.net/thread-643850-1-1.html
In addition
Yes, I ’m from cfpa.team, currently the largest Minecraft mods folk translation team in China
This is the work of our team:https://www.curseforge.com/minecraft/texture-packs/simplified-chinese-localization-resource-package

**Comment by Corail31** [comment]
Sure, thanks for the precision :)

**Comment by Aemande123** [comment]
> Sure, thanks for the precision :)

thank you very much！

**Pull request merged**
